# config – Konfiguration aus config.json (api_key etc.) + settings.json (UI-Einstellungen).
from .load import load_config
from .settings import (
    load_settings,
    save_settings,
    KEY_API_KEY,
    KEY_USE_CUSTOM_SMOOTHER,
    KEY_CUSTOM_SMOOTHER_SYSTEM,
    KEY_CUSTOM_SMOOTHER_USER,
    KEY_SMOOTHER_MODEL,
    DEFAULT_SMOOTHER_MODEL,
    KEY_HOTKEY_START_STOP,
    DEFAULT_HOTKEY_START_STOP,
    KEY_PROVIDER,
    KEY_AZURE_ENDPOINT_URL,
    KEY_AZURE_API_KEY,
    KEY_TRANSCRIBE_MODEL,
    DEFAULT_PROVIDER,
    DEFAULT_TRANSCRIBE_MODEL,
)

__all__ = [
    "load_config",
    "load_settings",
    "save_settings",
    "KEY_API_KEY",
    "KEY_USE_CUSTOM_SMOOTHER",
    "KEY_CUSTOM_SMOOTHER_SYSTEM",
    "KEY_CUSTOM_SMOOTHER_USER",
    "KEY_SMOOTHER_MODEL",
    "DEFAULT_SMOOTHER_MODEL",
    "KEY_HOTKEY_START_STOP",
    "DEFAULT_HOTKEY_START_STOP",
    "KEY_PROVIDER",
    "KEY_AZURE_ENDPOINT_URL",
    "KEY_AZURE_API_KEY",
    "KEY_TRANSCRIBE_MODEL",
    "DEFAULT_PROVIDER",
    "DEFAULT_TRANSCRIBE_MODEL",
]
